### PR TITLE
Refactor: Prometheus AWS discovery

### PR DESCRIPTION
**Pull request by envyj020**
This PR amends the original [upstream](https://github.com/DaspawnW/prometheus-aws-discovery) source code as their future feature plans will be unaligned with ours.

They are looking to introduce their **V2 tag scheme discovery:** 
```
key: exporters
value: [{"name": "node-exporter","port": 9100,"path": "metrics","scheme": "https"},{...},{...}]
```
AWS Tag's value limit is set to 1 byte - 256-1 chars, We'll definitely hit those limits for instances running many exporters following this scheme therefore instead this Go package is modified in order to:
1. Retrieve exporters by default, following this tagging convention:
```
key: prom/scrape:{EXPORTER_PORT}:{EXPORTER_SCHEME}/{EXPORTER_METRICS_PATH}
value: {EXPORTER_NAME}
```
2. Add a `--filter` option list where we can provide as many [EC2 API compliant filters](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html) so we can narrow down the amount of VM's based in our own partition domain.

Example:
```
$ ./prometheus-aws-discovery \
           --output=file \
           --file-path=targets.json \
           --filter="tag:Environment=mgmt" \
           --filter="availability-zone=eu-west-1a"
           
$ jq '{"root": .}' < targets.json

{
  "root": [
    {
      "targets": [
        "10.31.9.173:9100"
      ],
      "labels": {
        "__address__": "10.31.9.173:9100",
        "__metrics_path__": "/metrics",
        "__scheme__": "http",
        "ansible": "true",
        "environment": "mgmt",
        "fqdn": "devops-deployer-1.mgmt.eu-west-1.stuart",
        "instancename": "devops-deployer-1.mgmt",
        "name": "node_exporter",
        "provisioner": "Terraform",
        "role": "devops-deployer"
      }
    }
  ]
}
```
#### Concern
Since we are deviating far away from the initial intend of this package and especially because We'd need to consistently automate and produce our own binaries instead I'd suggest to maintain our own flavor privately in our organization but obviously pointing to the upstream source in its README, I don't really like the idea of publicly expose our internal processes but WDYT?

### CODE REVIEW

**Comment by mjimeneznet** [comment]
Seeing the amount of changes done (removal of CSV, AzureDevops, etc...) and is not only adding a new option to filter by tags or availability zone, it is totally different from the original project although it's based on it.

And yes, I will point to the origin of this script in the readme and maintain it private to Stuart, since there's no option to open a PR to the upstream repo with this changes :)

**Review by mjimeneznet — APPROVED** [review]

**Comment by vide** [comment]
Chipping in on the concern part: I don't think it's exposing any secret sauce internal process (beside that we are using prometheus on k8s and we might have several exporters installed on EC2 instances), and deviating so much from the original project might worth taking the time to automate the build in public with a public repo powered by GHA for the package build (so, keep it completely disconnected from our internal build systems).
OTOH the original license is MIT so we can modify and keep it private without any issue if we want...
But if I had to vote, I would go to make a public hard-fork.

**Review by kiyanabah — COMMENTED** [review]
Considering` IMPORTANT: The below applies to v1 tags. These will be deprecated soon`, In the original repo and our current taging is based on v1 tags and we need to enable the service discovery with this tag version for the moment, so I would also go with maintaining it in private to Stuart. And perhaps later as improvement we can move to the v2 tags in public repo.

**Review by vide — COMMENTED** [review]
Can you also remove mentions of the stripped out features from the README?

**Comment by envyj020** [comment]
Thanks for your feedback guys, You all raised valid concerns, for now I'll turn this repository private after merging but clearly reflecting from where it comes from and will add all the missing pieces to close the loop. Obviously we can always change the visibility back and resume our collaboration with upstream.

**Pull request merged**
